const array = ["Amrit Ranjan", 24, "amrit@google.com", true]
console.log(array)
console.log(array[3])
console.log(typeof array)
array.push("Graduates")
console.log(array)
array.pop()
console.log(array)
array.shift()
console.log(array)
array.unshift("Amrit Ranjan")
console.log(array)
array.includes(24)
console.log(array.includes(24))
